"""
Django settings for API project.

Generated by 'django-admin startproject' using Django 3.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(k7%02u@8%fazduivn3=3730owip$52q9jkyh4x8#u2m3@1!n6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'ckeditor',
    'c_admin',
    'c_user',
    'core',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'API.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'API.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.TokenAuthentication",
    )
}



# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

# STATIC_ROOT = BASE_DIR / 'static'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]


AUTH_USER_MODEL = 'core.User'

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True


CKEDITOR_CONFIGS = {
    'default': {
        # 'skin': 'moono',
        'height': 50,
        'width': '100%',
        'extraPlugins': ','.join([
            'autogrow',
        ]),
        # The maximum height that the editor can assume when
        # adjusting to content by using the Auto Grow feature.
        'autoGrow_maxHeight': 400,
        # Placehorlder
        # 'Description de votre article ou de votre service'
        # Removing auto-paragraph feature
        'enterMode': 2,
        # Allow vertical and horizontal resizing
        # 'resize_dir': 'both',
        # Full Page Mode allow to edit <html> to </html>
        # 'fullPage': True,
        # Avoid wird caracters in text
        'htmlEncodeOutput': False,
        'entities': False,
        'basicEntities': False,
        'entities_greek': False,
        'entities_latin': False,
        # Tootlbars definitions
        'toolbar_Basic': [
            ['Source', '-', 'Bold', 'Italic']
        ],
        'toolbar_YourCustomToolbarConfig': [
            {
                'name': 'basicstyles',
                'items': [
                    'Bold', 'Italic', 'Underline', 'Strike', 'Subscript',
                    'Superscript', '-', 'RemoveFormat'
                ]
            },
            {
                'name': 'paragraph',
                'items': [
                    'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-',
                    'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'
                ]
            },
            {
                'name': 'links',
                'items': [
                    'Link', 'Unlink'
                ]
            },
            {
                'name': 'insert',
                'items': [
                    'Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley',
                    'SpecialChar', 'PageBreak', 'Iframe'
                ]
            },
            '/',
            {
                'name': 'styles',
                'items': [
                    'Styles', 'Format', 'Font', 'FontSize'
                ]
            },
            {
                'name': 'colors',
                'items': [
                    'TextColor', 'BGColor'
                ]
            },
            {
                'name': 'tools',
                'items': [
                    'Maximize', 'ShowBlocks'
                ]
            },
        ],
        'toolbar': 'YourCustomToolbarConfig',
    },

    ##############################
    # Another Toolbar definition #
    ##############################
    'template_toolbar': {
        # 'skin': 'moono',
        # 'height': 50,
        'width': '100%',
        'external_plugin_resources': [(
            'onchange',
            '/static/ckeditor/ckeditor/plugins/onchange/',
            'plugin.js',
        )],
        # The maximum height that the editor can assume when
        # adjusting to content by using the Auto Grow feature.
        # 'autoGrow_maxHeight': 400,
        # Placehorlder
        # 'Description de votre article ou de votre service'
        # Removing auto-paragraph feature
        'enterMode': 2,
        # Allow vertical and horizontal resizing
        # 'resize_dir': 'both',
        # Full Page Mode allow to edit <html> to </html>
        'fullPage': True,
        # content filtering can be disabled to prevent CKEditor from
        # removing disallowed elements
        'allowedContent': True,
        # To get allowedContent to work, disable stylesheetparser plugin
        "removePlugins": "stylesheetparser",
        # Avoid wird caracters in text
        'htmlEncodeOutput': False,
        'entities': False,
        'basicEntities': False,
        'entities_greek': False,
        'entities_latin': False,
        'toolbar_Basic': [
            ['Source', '-', 'Bold', 'Italic']
        ],
        'toolbar_YourCustomToolbarConfig': [
            {
                'name': 'document',
                'items': [
                    'Source', '-', 'Save', 'NewPage', 'Preview', 'Print', '-', 'Templates'
                ]
            },
            {
                'name': 'clipboard',
                'items': [
                    'Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo'
                ]
            },
            {
                'name': 'editing',
                'items': [
                    'Find', 'Replace', '-', 'SelectAll'
                ]
            },
            {
                'name': 'forms',
                'items': [
                    'Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select',
                    'Button', 'ImageButton', 'HiddenField'
                ]
            },
            '/',
            {
                'name': 'basicstyles',
                'items': [
                    'Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-',
                    'RemoveFormat'
                ]
            },
            {
                'name': 'paragraph',
                'items': [
                    'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-',
                    'Blockquote', 'CreateDiv', '-',
                    'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-',
                    'BidiLtr', 'BidiRtl', 'Language'
                ]
            },
            {
                'name': 'links',
                'items': [
                    'Link', 'Unlink', 'Anchor'
                ]
            },
            {
                'name': 'insert',
                'items': [
                    'Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar',
                    'PageBreak', 'Iframe'
                ]
            },
            '/',
            {
                'name': 'styles',
                'items': [
                    'Styles', 'Format', 'Font', 'FontSize'
                ]
            },
            {
                'name': 'colors',
                'items': [
                    'TextColor', 'BGColor'
                ]
            },
            {
                'name': 'tools',
                'items': [
                    'Maximize', 'ShowBlocks'
                    ]
                },
            {
                'name': 'about',
                'items': [
                    'About'
                ]
            },
            '/',  # put this to force next toolbar on new line
            {
                'name': 'yourcustomtools',
                'items': [
                    # put the name of your editor.ui.addButton here
                    'Preview',
                    'Maximize',
                ]
            },
        ],
        'toolbar': 'YourCustomToolbarConfig',  # put selected toolbar config here
        'tabSpaces': 4,
        'extraPlugins': ','.join([
            # On change in Ckeditor
            'onchange',
            # the upload image feature
            'uploadimage',
            # @page properties
            # 'docprops'
            # your extra plugins here
            'div',
            'autolink',
            'autoembed',
            'embedsemantic',
            'autogrow',
            # 'devtools',
            'widget',
            'lineutils',
            'clipboard',
            'dialog',
            'dialogui',
            'elementspath'
        ]),
    }
}